const MOBILE_UA = 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1';
const DESKTOP_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36';

function json(res, status, body) {
  res.statusCode = status;
  res.setHeader('Content-Type', 'application/json; charset=utf-8');
  res.setHeader('Cache-Control', 's-maxage=120, stale-while-revalidate=600');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.end(JSON.stringify(body));
}
function decodeEntities(s = '') { return String(s).replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/\\u002F/g,'/'); }
function stripTags(s=''){return decodeEntities(String(s)).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/\s+/g,' ').trim();}
function pick(regex,text,group=1){const m=String(text||'').match(regex);return m?decodeEntities(String(m[group]||'').trim()):'';}
function hdImage(url=''){let u=decodeEntities(String(url||'').trim());if(!u)return'';u=u.replace(/\\\//g,'/');if(u.startsWith('//'))u='https:'+u;if(/pipi\.cn|meituan\.net|maoyan\.com/i.test(u))u=u.split('?')[0].replace(/@\d+w_\d+h.*$/i,'');return u;}
async function fetchText(url,ua=MOBILE_UA,referer='https://www.maoyan.com/'){const r=await fetch(url,{headers:{'User-Agent':ua,'Accept':'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8','Accept-Language':'zh-CN,zh;q=0.9,en;q=0.5','Referer':referer},redirect:'follow'});const text=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status} ${url}`);return text;}

function collectMovies(value,out=[],seen=new Set()){
  if(!value||typeof value!=='object')return out;
  if(Array.isArray(value)){for(const item of value)collectMovies(item,out,seen);return out;}
  const id=value.id||value.movieId||value.movieid;const name=value.nm||value.name||value.movieName||value.title;
  if(id&&name&&!seen.has(String(id))){seen.add(String(id));out.push({id:String(id),name:String(name),english_name:value.enm||value.enName||'',poster:hdImage(value.img||value.poster||value.pic||''),category:value.cat||value.type||'',director:value.dir||'',actors:value.star||value.actors||'',release_date:value.rt||value.releaseDate||value.showInfo||'',duration:value.dur||value.duration||'',score:value.sc??value.score??null,wish:value.wish??null});}
  for(const v of Object.values(value))collectMovies(v,out,seen);return out;
}

function parseDetail(html,id){
  let name=pick(/<meta\s+name=["']share:wechat:message:title["']\s+content=["']《([^》]+)》/i,html);
  const scoreFromShare=pick(/<meta\s+name=["']share:wechat:message:title["']\s+content=["'][^"']*猫眼购票评分([\d.]+)/i,html);
  if(!name)name=pick(/<div[^>]+class=["'][^"']*movie-cn-name[^"']*["'][^>]*>[\s\S]*?<h1[^>]*>([^<]+)<\/h1>/i,html);if(!name)name=pick(/<title>([^_<]+)_购票/i,html);
  const englishName=pick(/<div[^>]+class=["'][^"']*movie-en-name[^"']*["'][^>]*>([^<]*)<\/div>/i,html);const category=pick(/<span[^>]+class=["'][^"']*movie-cat[^"']*["'][^>]*>([^<]+)<\/span>/i,html);const showTime=stripTags(pick(/<div[^>]+class=["'][^"']*movie-show-time[^"']*["'][^>]*>([\s\S]*?)<\/div>/i,html));const score=scoreFromShare||pick(/<span[^>]+class=["'][^"']*score[^"']*["'][^>]*>([\d.]+)<\/span>/i,html);const scoreCount=pick(/([\d,]+)\s*人评/i,stripTags(html));const description=pick(/<meta\s+name=["']share:wechat:message:desc["']\s+content=["']简介\|([^"']*)["']/i,html)||pick(/<meta\s+name=["']description["']\s+content=["']([^"']*)["']/i,html);const poster=hdImage(pick(/<meta\s+name=["']share:wechat:message:icon["']\s+content=["']([^"']+)["']/i,html));const duration=Number(pick(/(\d+)\s*分钟/i,showTime+' '+stripTags(html)))||null;
  const actorBlock=pick(/<div[^>]+class=["'][^"']*actors[^"']*["'][^>]*>([\s\S]*?)<\/div>/i,html);const actors=[];const actorRe=/<a\s+href=["']\/asgard\/celebrity\/(\d+)["'][^>]*>([^<]+)<\/a>/gi;let am;while((am=actorRe.exec(actorBlock)))actors.push({id:am[1],name:stripTags(am[2]).replace(/\s*\/\s*$/,''),url:`https://piaofang.maoyan.com/celebrity?id=${am[1]}`});
  return{id:String(id),name,english_name:englishName,category,show_time:showTime,duration_min:duration,score:score?Number(score):null,score_count:scoreCount?Number(scoreCount.replace(/,/g,'')):null,description,poster,poster_hd:poster,actors,source_url:`https://m.maoyan.com/asgard/movie/${id}`};
}

function parsePerson(html,id,sourceUrl){
  const text=stripTags(html);let name=pick(/<h1[^>]*>([^<]{1,80})<\/h1>/i,html)||pick(/<title>([^_<]{1,80})/i,html);name=name.replace(/介绍_图片_作品-猫眼电影.*/,'').trim();
  let avatar=hdImage(pick(/<meta[^>]+(?:property|name)=["'](?:og:image|share:wechat:message:icon)["'][^>]+content=["']([^"']+)["']/i,html));
  if(!avatar){const cdn=[...String(html).matchAll(/https?:\\?\/\\?\/(?:p\d\.pipi\.cn|p\d\.meituan\.net)\/[A-Za-z0-9_\-/]+\.(?:jpg|jpeg|png)(?:[^"'\s<]*)?/gi)].map(x=>hdImage(x[0]));avatar=cdn.find(u=>/basicdata|moviemachine|movie/i.test(u))||cdn[0]||'';}
  const en=pick(/(?:英文名|英文名称)[：:\s]*([^\s<]{2,60})/i,text)||'';const desc=pick(/<meta\s+name=["']description["']\s+content=["']([^"']+)["']/i,html);
  return{id:String(id),name,english_name:en,avatar,description:desc,text_excerpt:text.slice(0,1000),source_url:sourceUrl};
}

function parseAjaxExtra(html){const text=stripTags(html),boxOffice={};const re=/([\d.]+)\s*(万|亿)?\s*(首日票房|首周票房|累计票房|总票房)/g;let m;while((m=re.exec(text))){const raw=Number(m[1]),unit=m[2]||'',label=m[3];boxOffice[label]={display:`${m[1]}${unit||'万'}`,value_wan:unit==='亿'?raw*10000:raw};}function section(label,next){const i=text.indexOf(label);if(i<0)return'';let e=text.length;for(const n of next){const p=text.indexOf(n,i+label.length);if(p>=0&&p<e)e=p;}return text.slice(i+label.length,Math.min(e,i+label.length+800)).trim();}return{box_office:boxOffice,publisher:section('出品发行',['技术参数','幕后花絮','获奖','荣誉']),tech_param:section('技术参数',['幕后花絮','获奖','荣誉','出品发行']),behind_the_scenes:section('幕后花絮',['获奖','荣誉','出品发行','技术参数']),raw_text_excerpt:text.slice(0,3000)};}

function parseGallery(html,movieId,sourceUrl){const map=new Map();const raw=String(html||'');for(const m of raw.matchAll(/<img[^>]+(?:src|data-src)=["']([^"']+)["'][^>]*>/gi)){const tag=m[0],u=hdImage(m[1]);if(!u||!/pipi\.cn|meituan\.net/i.test(u))continue;const ctx=raw.slice(Math.max(0,(m.index||0)-250),Math.min(raw.length,(m.index||0)+350));if(/剧照|图集|movie-img|album|img\d|海报/i.test(tag+' '+ctx))map.set(u,{url:u,type:/海报|poster/i.test(tag+' '+ctx)?'poster':'still',source_url:sourceUrl});}return{movie_id:String(movieId),count:map.size,images:[...map.values()].slice(0,40)};}

function mergeGalleries(results,movieId){const m=new Map();for(const r of results||[])for(const x of r?.images||[])if(x.url)m.set(x.url,x);return{movie_id:String(movieId),count:m.size,images:[...m.values()]};}

function parseVideoAnchors(html,movieId){const raw=String(html||''),map=new Map();const anchor=/<a[^>]+href=["']([^"']*(?:preview\?videoId=|videoId=)(\d+)[^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=anchor.exec(raw))){const id=m[2],block=m[3],old=map.get(id)||{};const text=stripTags(block);const title=text.length>2&&!/^Image$/i.test(text)?text:'';const cover=hdImage(pick(/<img[^>]+(?:src|data-src)=["']([^"']+)["']/i,block));map.set(id,{...old,video_id:id,title:(title.length>(old.title||'').length?title:old.title)||'',cover:old.cover||cover,source_page_url:m[1].startsWith('http')?m[1]:`https://www.maoyan.com${m[1]}`,direct_media_url:null});}
  for(const x of raw.matchAll(/(?:data-val=["'][^"']*videoId\s*:\s*|[?&]videoId=|\"videoId\"\s*:\s*)(\d+)/gi)){const id=x[1];if(!map.has(id))map.set(id,{video_id:id,title:'',cover:'',source_page_url:`https://www.maoyan.com/films/${movieId}/preview?videoId=${id}`,direct_media_url:null});}
  return [...map.values()];
}

function parseVideos(html,movieId,sourceUrl){const raw=String(html||''),text=stripTags(raw);const trailerCount=Number(pick(/预告片\s*(\d+)/,text))||0,officialCount=Number(pick(/官方视频\s*(\d+)/,text))||0;let videos=parseVideoAnchors(raw,movieId);
  // 对缺标题的条目，从 videoId 附近取文本/封面。
  videos=videos.map(v=>{const pos=raw.indexOf(v.video_id);const win=pos>=0?raw.slice(Math.max(0,pos-900),Math.min(raw.length,pos+1500)):'';const wt=stripTags(win);let title=v.title||pick(/(?:videoName|videoTitle|title|name)\s*["']?\s*[:=]\s*["']([^"']{3,180})["']/i,win);if(/^(safari|image)$/i.test(title))title='';const duration=pick(/\b(\d{1,2}:\d{2})\b/,wt);const playCount=pick(/([\d.]+\s*(?:万|亿))\s*(?:次播放|播放)?/,wt);const cover=v.cover||hdImage(pick(/<img[^>]+(?:src|data-src)=["']([^"']+)["']/i,win));let type=/预告|trailer|先导|IMAX预告|终极预告/i.test(title)?'trailer':'official';return{...v,title,duration,play_count:playCount,cover,type};});
  const heur=videos.filter(v=>v.type==='trailer');if(trailerCount&&videos.length>=trailerCount&&heur.length<trailerCount){for(const v of videos){if(heur.length>=trailerCount)break;if(v.type!=='trailer'){v.type='trailer';heur.push(v);}}}
  return{movie_id:String(movieId),count:videos.length,trailer_count:trailerCount||videos.filter(v=>v.type==='trailer').length,official_count:officialCount||videos.filter(v=>v.type!=='trailer').length,videos,source_url:sourceUrl};}

function mergeVideoResults(results,movieId){const map=new Map();let trailerCount=0,officialCount=0;for(const r of results){if(!r||!Array.isArray(r.videos))continue;trailerCount=Math.max(trailerCount,r.trailer_count||0);officialCount=Math.max(officialCount,r.official_count||0);for(const v of r.videos){const old=map.get(v.video_id)||{};map.set(v.video_id,{...old,...v,title:v.title&&v.title.length>(old.title||'').length?v.title:(old.title||v.title),cover:old.cover||v.cover,duration:old.duration||v.duration,play_count:old.play_count||v.play_count,type:old.type==='trailer'||v.type==='trailer'?'trailer':'official'});}}const videos=[...map.values()];if(trailerCount&&videos.length>=trailerCount&&videos.filter(v=>v.type==='trailer').length<trailerCount){for(const v of videos){if(videos.filter(x=>x.type==='trailer').length>=trailerCount)break;if(v.type!=='trailer')v.type='trailer';}}return{movie_id:String(movieId),count:videos.length,trailer_count:trailerCount||videos.filter(v=>v.type==='trailer').length,official_count:officialCount||videos.filter(v=>v.type!=='trailer').length,videos};}

function parsePlayable(html){const raw=String(html||'');let url=pick(/<video[^>]+src=["']([^"']+)["']/i,raw)||pick(/<source[^>]+src=["']([^"']+)["']/i,raw)||pick(/(?:videoUrl|playUrl|url)\s*["']?\s*[:=]\s*["'](https?:\\?\/\\?\/[^"']+\.(?:mp4|m3u8)[^"']*)["']/i,raw);url=decodeEntities(url).replace(/\\\//g,'/');if(url.startsWith('//'))url='https:'+url;const poster=hdImage(pick(/<video[^>]+poster=["']([^"']+)["']/i,raw));const title=pick(/<title>([^<]+)<\/title>/i,raw);return{direct_media_url:url,cover:poster,title};}
async function enrichPlayable(v,movieId){const urls=[`https://m.maoyan.com/prevue/${v.video_id}`,`https://m.maoyan.com/asgard/feedVideos/index?videoId=${v.video_id}`,`https://www.maoyan.com/films/${movieId}/preview?videoId=${v.video_id}`];for(const u of urls){try{const h=await fetchText(u,MOBILE_UA,`https://m.maoyan.com/asgard/movie/${movieId}/preview`);const p=parsePlayable(h);if(p.direct_media_url||p.cover||p.title)return{...v,direct_media_url:p.direct_media_url||v.direct_media_url,cover:v.cover||p.cover,title:v.title||p.title,play_source:u};}catch{}}return v;}

module.exports=async function handler(req,res){const started=Date.now(),action=String(req.query.action||'status'),fetchedAt=new Date().toISOString();try{
  if(action==='status')return json(res,200,{ok:true,provider:'maoyan',status:'ACTIVE',fetched_at:fetchedAt,capabilities:['search','detail','people','images','boxoffice','videos']});
  if(action==='search'){const q=String(req.query.q||'').trim();if(!q)return json(res,400,{ok:false,error:'missing q'});const url=`https://m.maoyan.com/apollo/ajax/search?kw=${encodeURIComponent(q)}&cityId=1&stype=-1`;const text=await fetchText(url);let data;try{data=JSON.parse(text)}catch{throw new Error('search response is not JSON')}const movies=collectMovies(data).slice(0,30);return json(res,200,{ok:true,provider:'maoyan',action,query:q,fetched_at:fetchedAt,latency_ms:Date.now()-started,count:movies.length,movies,source_url:url});}
  if(action==='people'){const ids=String(req.query.ids||'').split(',').map(x=>x.trim()).filter(x=>/^\d+$/.test(x)).slice(0,8);if(!ids.length)return json(res,400,{ok:false,error:'missing ids'});const people=await Promise.all(ids.map(async id=>{const urls=[`https://piaofang.maoyan.com/celebrity?id=${id}`,`https://piaofang.maoyan.com/celebrity/${id}`,`https://m.maoyan.com/asgard/celebrity/${id}`];for(const u of urls){try{return parsePerson(await fetchText(u,DESKTOP_UA,'https://piaofang.maoyan.com/'),id,u)}catch{}}return{id,name:'',avatar:'',error:'all person sources failed'}}));return json(res,200,{ok:true,provider:'maoyan',action,fetched_at:fetchedAt,latency_ms:Date.now()-started,people});}
  const id=String(req.query.id||'').trim();if(!/^\d+$/.test(id))return json(res,400,{ok:false,error:'missing/invalid id'});
  if(action==='detail'){const mobileUrl=`https://m.maoyan.com/asgard/movie/${id}`,ajaxUrl=`https://www.maoyan.com/ajax/films/${id}`;const[detailR,extraR]=await Promise.allSettled([fetchText(mobileUrl,MOBILE_UA),fetchText(ajaxUrl,DESKTOP_UA)]);if(detailR.status!=='fulfilled')throw detailR.reason;const detail=parseDetail(detailR.value,id);const extra=extraR.status==='fulfilled'?parseAjaxExtra(extraR.value):{box_office:{},publisher:'',tech_param:'',behind_the_scenes:'',error:String(extraR.reason||'')};return json(res,200,{ok:true,provider:'maoyan',action,fetched_at:fetchedAt,latency_ms:Date.now()-started,movie:{...detail,...extra},sources:{detail:mobileUrl,extra:ajaxUrl}});}
  if(action==='images'){const urls=[`https://imovie.pipi.cn/films/${id}`,`https://www.maoyan.com/films/${id}`,`https://m.maoyan.com/asgard/movie/${id}`];const rs=await Promise.allSettled(urls.map((u,i)=>fetchText(u,i===2?MOBILE_UA:DESKTOP_UA)));const parsed=rs.map((r,i)=>r.status==='fulfilled'?parseGallery(r.value,id,urls[i]):null).filter(Boolean);const merged=mergeGalleries(parsed,id);return json(res,200,{ok:true,provider:'maoyan',action,fetched_at:fetchedAt,latency_ms:Date.now()-started,...merged,sources:rs.map((r,i)=>({url:urls[i],status:r.status}))});}
  if(action==='videos'){const urls=[`https://imovie.pipi.cn/films/${id}/preview`,`https://qqw.maoyan.com/asgard/movie/${id}/preview`,`https://www.maoyan.com/films/${id}/preview`,`https://m.maoyan.com/asgard/movie/${id}/preview`];const rs=await Promise.allSettled(urls.map((u,i)=>fetchText(u,i===1||i===3?MOBILE_UA:DESKTOP_UA,`https://www.maoyan.com/films/${id}`)));const parsed=rs.map((r,i)=>r.status==='fulfilled'?parseVideos(r.value,id,urls[i]):null).filter(Boolean);if(!parsed.length)throw new Error('all video sources failed');let merged=mergeVideoResults(parsed,id);const trailerIndexes=merged.videos.map((v,i)=>v.type==='trailer'?i:-1).filter(i=>i>=0).slice(0,4);const enriched=await Promise.all(trailerIndexes.map(i=>enrichPlayable(merged.videos[i],id)));trailerIndexes.forEach((idx,j)=>{merged.videos[idx]=enriched[j]});return json(res,200,{ok:true,provider:'maoyan',action,fetched_at:fetchedAt,latency_ms:Date.now()-started,...merged,sources:urls,source_status:rs.map((r,i)=>({url:urls[i],status:r.status,error:r.status==='rejected'?String(r.reason):''}))});}
  return json(res,404,{ok:false,error:`unknown action: ${action}`});
}catch(error){return json(res,502,{ok:false,provider:'maoyan',action,status:'FETCH_FAILED',fetched_at:fetchedAt,latency_ms:Date.now()-started,error:error&&error.message?error.message:String(error)});}};
