const MOBILE_UA='Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1';
const DESKTOP_UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36';
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','s-maxage=120, stale-while-revalidate=600');res.setHeader('Access-Control-Allow-Origin','*');res.end(JSON.stringify(body))}
function dec(s=''){return String(s).replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/\\u002F/g,'/')}
function strip(s=''){return dec(String(s)).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/\s+/g,' ').trim()}
function pick(re,s,g=1){const m=String(s||'').match(re);return m?dec(String(m[g]||'').trim()):''}
function image(u=''){u=dec(String(u||'').trim()).replace(/\\\//g,'/');if(u.startsWith('//'))u='https:'+u;if(u.startsWith('http://'))u='https://'+u.slice(7);return u}
async function text(url,ua=MOBILE_UA,ref='https://m.maoyan.com/'){const r=await fetch(url,{headers:{'User-Agent':ua,'Accept':'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8','Accept-Language':'zh-CN,zh;q=0.9','Referer':ref},redirect:'follow'});const s=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status} ${url}`);return s}
function parseAnchors(html,movieId,source){const raw=String(html||''),map=new Map();const add=(id,obj={})=>{id=String(id||'');if(!/^\d+$/.test(id))return;map.set(id,{...(map.get(id)||{}),video_id:id,source_url:source,...obj})};
  for(const m of raw.matchAll(/<a[^>]+href=["']([^"']*(?:preview\?[^"']*videoId=|videoId=)(\d+)[^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi)){const href=dec(m[1]),block=m[3],t=strip(block);add(m[2],{title:t&&!/^Image$/i.test(t)&&t.length<220?t:'',cover:image(pick(/<img[^>]+(?:src|data-src)=["']([^"']+)["']/i,block)),source_page_url:href.startsWith('http')?href:`https://m.maoyan.com${href}`})}
  for(const m of raw.matchAll(/(?:data-val=["'][^"']*videoId\s*:\s*|[?&]videoId=|\"videoId\"\s*:\s*)(\d+)/gi))add(m[1],{source_page_url:`https://m.maoyan.com/asgard/movie/${movieId}/preview?videoId=${m[1]}`});
  for(const m of raw.matchAll(/data-id=["'](\d+)["'][^>]*data-lab=["'][^"']*video_id[^"']*/gi))add(m[1],{});
  return [...map.values()].map(v=>{const pos=raw.indexOf(v.video_id),win=pos>=0?raw.slice(Math.max(0,pos-1200),Math.min(raw.length,pos+2000)):'';let title=v.title||pick(/(?:videoName|videoTitle|title|name)\s*["']?\s*[:=]\s*["']([^"']{3,180})["']/i,win);if(/^(safari|image)$/i.test(title))title='';return{...v,title,cover:v.cover||image(pick(/<img[^>]+(?:src|data-src)=["']([^"']+)["']/i,win)),duration:pick(/\b(\d{1,2}:\d{2})\b/,strip(win)),type:/预告|trailer|先导|IMAX|终极|定档/i.test(title)?'trailer':'unknown'}})}
function counts(html){const t=strip(html);return{trailer:Number(pick(/预告片\s*(\d+)/,t))||0,official:Number(pick(/官方视频\s*(\d+)/,t))||0}}
function playable(html){const raw=String(html||'');let url=pick(/<video[^>]+src=["']([^"']+)["']/i,raw)||pick(/<source[^>]+src=["']([^"']+)["']/i,raw)||pick(/(?:videoUrl|videourl|playUrl|\"url\")\s*["']?\s*[:=]\s*["'](https?:\\?\/\\?\/[^"']+\.(?:mp4|m3u8)[^"']*)["']/i,raw);url=dec(url).replace(/\\\//g,'/');if(url.startsWith('//'))url='https:'+url;return{direct_media_url:url,cover:image(pick(/(?:poster|imgUrl|image)["']?\s*[:=]\s*["']([^"']+)["']/i,raw)||pick(/<video[^>]+poster=["']([^"']+)["']/i,raw)),title:pick(/<title>([^<]+)<\/title>/i,raw)}}
async function enrich(v,movieId){const urls=[v.source_page_url,`https://m.maoyan.com/prevue/${v.video_id}`,`https://m.maoyan.com/asgard/feedVideos/index?videoId=${v.video_id}`,`https://m.maoyan.com/asgard/movie/${movieId}/preview?videoId=${v.video_id}`,`https://www.maoyan.com/films/${movieId}/preview?videoId=${v.video_id}`].filter(Boolean);for(const u of [...new Set(urls)]){try{const p=playable(await text(u,u.includes('www.maoyan.com')?DESKTOP_UA:MOBILE_UA,`https://m.maoyan.com/asgard/movie/${movieId}/preview`));if(p.direct_media_url)return{...v,title:v.title||p.title,cover:v.cover||p.cover,direct_media_url:p.direct_media_url,play_source:u}}catch{}}return v}
function rank(v){const t=String(v.title||'');if(/首支|首曝/.test(t))return 0;if(/正式|终极|定档/.test(t))return 1;if(/第二支|IMAX|预告/.test(t)&&!/番外|花絮|彩蛋|片段/.test(t))return 2;if(/番外|花絮|彩蛋|片段|幕后/.test(t))return 9;return 5}
module.exports=async function(req,res){const started=Date.now(),id=String(req.query.id||'');if(!/^\d+$/.test(id))return json(res,400,{ok:false,error:'missing/invalid id'});try{const urls=[`https://imovie.pipi.cn/films/${id}/preview`,`https://qqw.maoyan.com/asgard/movie/${id}/preview`,`https://www.maoyan.com/films/${id}/preview`,`https://m.maoyan.com/asgard/movie/${id}/preview`];const rs=await Promise.allSettled(urls.map((u,i)=>text(u,i===1||i===3?MOBILE_UA:DESKTOP_UA,`https://m.maoyan.com/asgard/movie/${id}`)));const map=new Map();let trailerCount=0,officialCount=0;rs.forEach((r,i)=>{if(r.status!=='fulfilled')return;const c=counts(r.value);trailerCount=Math.max(trailerCount,c.trailer);officialCount=Math.max(officialCount,c.official);for(const v of parseAnchors(r.value,id,urls[i])){const old=map.get(v.video_id)||{};map.set(v.video_id,{...old,...v,title:(v.title&&v.title.length>(old.title||'').length)?v.title:(old.title||v.title||''),cover:old.cover||v.cover||'',type:old.type==='trailer'||v.type==='trailer'?'trailer':'unknown'})}});let all=[...map.values()];if(trailerCount&&all.length>=trailerCount&&all.filter(x=>x.type==='trailer').length<trailerCount){const likely=[...all].sort((a,b)=>rank(a)-rank(b));for(const v of likely){if(all.filter(x=>x.type==='trailer').length>=trailerCount)break;if(v.type!=='trailer')v.type='trailer'}}const candidates=all.filter(v=>v.type==='trailer').slice(0,Math.max(4,trailerCount||4));const enriched=await Promise.all(candidates.map(v=>enrich(v,id)));const videos=enriched.filter(v=>v.direct_media_url).map(v=>({...v,type:'trailer'})).sort((a,b)=>rank(a)-rank(b));return json(res,200,{ok:true,provider:'maoyan',movie_id:id,count:videos.length,trailer_count:trailerCount||videos.length,official_count:officialCount,videos,latency_ms:Date.now()-started,sources:urls,source_status:rs.map((r,i)=>({url:urls[i],status:r.status,error:r.status==='rejected'?String(r.reason):''}))})}catch(e){return json(res,502,{ok:false,error:e.message||String(e),latency_ms:Date.now()-started})}}
